//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSecretLog
    {
        public int ID { get; set; }
        public int AppID { get; set; }
        public string Secret { get; set; }
        public System.DateTime InputTime { get; set; }
    }
}
