//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.SP.IDBuilder
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public  class IDSeed
    {
        [Key]
        
        public int ID { get; set; }
        public int TotalCount { get; set; }
        public int DayCount { get; set; }
        public System.DateTime SeedDay { get; set; }
        public System.DateTime RefreshTime { get; set; }       
    }
}
