//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Model.XApp
{
    
    
    public class AppSecret
    {
        [Key]
        public int ID { get; set; }
        public string Secret { get; set; }
        public string SecretPre { get; set; }
        public System.DateTime RefreshTime { get; set; }
        public System.DateTime PreTime { get; set; }
        public System.DateTime TimeOutTime { get; set; }
    }
}
